modules:
  spectralviewer: view_spectra
  resampler: resample
  wavheader_editor: wavheader_editor
  yaml_editor: yaml_editor
  annotator: annotate
  synthesizer: synthesizer
module_names:
  spectralviewer: View Spectra
  resampler: Resampler
  wavheader_editor: Wavheader Editor
  yaml_editor: Yaml Editor
  annotator: Annotator
  synthesizer: Synthesizer
